export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#43474e",
        "on-secondary-fixed-variant": "#40484e",
        "primary-fixed-dim": "#aec8f4",
        "on-secondary-fixed": "#151d22",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed-variant": "#005313",
        "surface-tint": "#465f86",
        secondary: "#575f66",
        "primary-fixed": "#d5e3ff",
        "inverse-primary": "#aec8f4",
        "surface-dim": "#d8dadc",
        "on-tertiary-container": "#55b857",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001c3b",
        background: "#f7f9fb",
        "tertiary-fixed-dim": "#78dc77",
        "on-error": "#ffffff",
        "on-primary-container": "#8ba4cf",
        error: "#ba1a1a",
        "tertiary-container": "#00440e",
        "secondary-fixed-dim": "#bfc7cf",
        "surface-variant": "#e0e3e5",
        primary: "#032448",
        "on-primary-fixed-variant": "#2d476d",
        tertiary: "#002b06",
        "surface-container": "#eceef0",
        surface: "#f7f9fb",
        "secondary-fixed": "#dbe3eb",
        "on-tertiary-fixed": "#002204",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "outline-variant": "#c4c6cf",
        "surface-bright": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "secondary-container": "#dbe3eb",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1f3a5f",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#5d656c",
        outline: "#74777f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "16px",
        xl: "24px",
        full: "9999px",
        md: "10px",
      },
      fontFamily: {
        headline: ["Inter"],
        display: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};